#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

#include <Camera.h>

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 200
#define FLOOR_HEIGHT 80

#define HEALTHBAR_HEIGHT 12
#define HEALTHBAR_WIDTH 35

#define COLLISION_TYPE_NONE 0
#define COLLISION_TYPE_PLAYER 1
#define COLLISION_TYPE_BULLET_PLAYER 2
#define COLLISION_TYPE_BULLET_ENEMY 3
#define COLLISION_TYPE_ENEMY  4
Camera* camera;

#endif
